version: '3.4'
services: 
  parser:
    image: mattiashem/parser
    command: ["-c", "/fluentd/etc/fluent.conf", "-v"]
    volumes:
      - ./input:/opt/input
      - ./output:/opt/output
      - ./state:/opt/state
      - ./etc:/fluentd/etc

     
